name: "Check"

on:
  pull_request:
    branches: ["master"]

jobs:
 check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - uses: pnpm/action-setup@v3
        with:
          version: 9.0.6
      - name: install
        run: pnpm install

      - name: pnpm build
        run: pnpm build
        env:
          GITHUB_PAGES: true
