name: deploy


on:
  push:
    branches:
      - master


jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run sh
        run: sh ./.github/deploy.sh
